---
app_dir: "/opt/flight-reservation-service"
is_demo: "{{ lookup('env', 'IS_DEMO') | default('false', true) | bool }}"

postgres_user: "{{ lookup('env', 'POSTGRES_USER') | default('db_user', true) }}"
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
postgres_db: "{{ lookup('env', 'POSTGRES_DB') | default('flight_reservation_db', true) }}"

valkey_password: "{{ lookup('env', 'VALKEY_PASSWORD') }}"

jwt_secret_key: "{{ lookup('env', 'JWT_SECRET_KEY') }}"

seed_admin_email: "{{ lookup('env', 'SEED_ADMIN_EMAIL') | default('admin@demo.local', true) }}"
seed_admin_password: "{{ lookup('env', 'SEED_ADMIN_PASSWORD') }}"
spring_profiles_active: "{{ lookup('env', 'SPRING_PROFILES_ACTIVE') | default('prod', true) }}"

app_image_tag: "{{ lookup('env', 'APP_IMAGE_TAG') | default('latest', true) }}"

domain: "{{ lookup('env', 'DOMAIN') | default('localhost', true) }}"
trusted_proxies: "{{ lookup('env', 'TRUSTED_PROXIES') | default('', true) }}"
tls_cert: "{{ lookup('env', 'TLS_CERT') | default('', true) }}"
tls_key: "{{ lookup('env', 'TLS_KEY') | default('', true) }}"

grafana_admin_user: "{{ lookup('env', 'GRAFANA_ADMIN_USER') | default('admin', true) }}"
grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"
