---
app_dir: "/opt/flight-reservation-service"

db_user: "{{ lookup('env', 'DB_USER') | default('db_user', true) }}"
db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
db_name: "{{ lookup('env', 'DB_NAME') | default('flight_reservation_db', true) }}"

valkey_password: "{{ lookup('env', 'VALKEY_PASSWORD') }}"

spring_profiles_active: "{{ lookup('env', 'SPRING_PROFILES_ACTIVE') | default('prod', true) }}"

app_image_tag: "{{ lookup('env', 'APP_IMAGE_TAG') | default('latest', true) }}"

domain: "{{ lookup('env', 'DOMAIN') | default('localhost', true) }}"
trusted_proxies: "{{ lookup('env', 'TRUSTED_PROXIES') | default('', true) }}"
tls_cert: "{{ lookup('env', 'TLS_CERT') | default('', true) }}"
tls_key: "{{ lookup('env', 'TLS_KEY') | default('', true) }}"

grafana_admin_user: "{{ lookup('env', 'GRAFANA_ADMIN_USER') | default('admin', true) }}"
grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"
