---
- name: Add Docker Repository
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components:
      - stable
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install Docker and Docker Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add standard user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
